version: "3"
services:
    redis:
        container_name: dc-redis
        image: redis:latest
        networks:
            - redis
        ports:
            - 6379:6379
        restart: always
        tty: true
        volumes:
            - ./redis-data:/data
    redis-commander:
        command: --redis-host redis
        container_name: dc-redis-commander
        depends_on:
            - redis
        image: tenstartups/redis-commander:latest
        links:
            - redis
        networks:
            - redis
        ports:
            - 8082:8081
        restart: always
        tty: true
    phpredmin:
        # acount: admin
        # password: admin
        container_name: dc-phpredmin
        depends_on:
            - redis
        environment:
            - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
        image: sasanrose/phpredmin:latest
        links:
            - redis
        networks:
            - redis
        ports:
            - 8083:80
        restart: always
        tty: true

networks:
    redis:
        driver: bridge
