version: '3'
services:
  jenkins:
    container_name: dc-jenkins
    image: jenkins/jenkins:latest
    networks:
      - nw-jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    restart: always
    tty: true
    volumes:
      - "./jenkins-home:/var/jenkins_home"

networks:
  nw-jenkins:
    driver: bridge
