# Create Docker Network

# docker network create \
#     --driver macvlan \
#     --subnet 10.0.0.0/8 \
#     --gateway 10.0.0.1  \
#     --opt parent enp0s31f6 \
#     pub_net

# https://docs.gitlab.com/omnibus/docker/README.html
# Use the following command to edit gitlab.rb:
# sudo docker exec -it dc-gitlab vi /etc/gitlab/gitlab.rb
# sudo docker exec -it dc-gitlab gitlab-ctl reconfigure

version: '3'
services:
    gitlab:
        container_name: dc-gitlab
        image: gitlab/gitlab-ce:latest@sha256:352ae9d36a702252603f6c53a0b50b885c1e42ce47094bfb02de31687ac57679
        environment:
            GITLAB_ROOT_PASSWORD: xxxx
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://10.0.20.0'
        expose:
            - '22'
            - '80'
            - '433'
        hostname: 10.0.20.0
        networks:
            pub_net:
                ipv4_address: 10.0.20.0
        restart: always
        tty: true
        volumes:
            - ./gitlab-data:/var/opt/gitlab
            - ./gitlab-log:/var/log/gitlab
            - ./gitlab-config:/etc/gitlab
networks:
    pub_net:
        external: true
