version: '3'
services:
    gitlab:
        container_name: dc-gitlab
        image: gitlab/gitlab-ce:latest
        environment:
            # GITLAB_ROOT_PASSWORD: xxxxxxxx
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://gitlab'
        networks:
            - nw-gitlab
        ports:
            - '80:80'
            - '443:443'
            - '22:22'
        restart: always
        tty: true
        volumes:
            - ./gitlab-data:/var/opt/gitlab
            - ./gitlab-log:/var/log/gitlab
            - ./gitlab-config:/etc/gitlab
networks:
    nw-gitlab:
      driver: bridge
