version: '3'
services:
    postgres:
        container_name: dc-postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: xxxx
            POSTGRES_DB: user_db
        image: postgres:latest
        networks:
            - postgres
        ports:
            - 5432:5432
        restart: always
        tty: true
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
    pgadmin4:
        container_name: dc-pgadmin4
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: grammy.jiang@gmail.com
            PGADMIN_DEFAULT_PASSWORD: xxxx
        image: dpage/pgadmin4:latest
        links:
            - postgres
        networks:
            - postgres
        ports:
            - 80:80
        restart: always
        tty: true
networks:
    postgres:
        driver: bridge

