version:
services:
  rancher:
    container_name: dc-rancher
    image: rancher/server:stable@sha256:2e53f0731ea82e1bce4bd77df26a98c5b26510c84fd8916f956424b4c2158472
    ports:
      - '8080:8080'
    restart: always
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql