version:
services:
  rancher:
    container_name: dc-rancher
    image: rancher/server:stable@sha256:95b55603122c28baea4e8d94663aa34ad770bbc624a9ed6ef986fb3ea5224d91
    ports:
      - '8080:8080'
    restart: always
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql