version:
services:
  rancher:
    container_name: dc-rancher
    image: rancher/server:stable@sha256:4119159ed0f5a53c79af5d0eaa4c7de31c42bd411eac4756f8e2ce56fb37b43a
    ports:
      - '8080:8080'
    restart: always
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql