version:
services:
  rancher:
    container_name: dc-rancher
    image: rancher/server:stable@sha256:b06394281b22a84c439d82095c88d2ae0e68694791c257780e207bb0fbfb15ad
    ports:
      - '8080:8080'
    restart: always
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql