#!/bin/bash
# This hook is sourced after a new virtualenv is activated.

# data science
pip install ipython
pip install jupyter

pip install numpy
pip install pandas

pip install sympy
pip install nose

pip install scipy
pip install scikit-image
pip install scikit-learn

pip install matplotlib

# c extensions
pip install cython

# functional programming
pip install fn
pip install toolz
pip install cytoolz
pip install multipledispatch
pip install pyrsistent

# devops
pip install docker
pip install raven
pip install versioneer

# database
pip install pymongo
pip install redis

# web development
pip install uvloop
pip install sanic

# mq
pip install celery
pip install flower

# misc.
pip install mitmproxy
pip install jedi
pip install cookiecutter
