#!/bin/bash
# This hook is sourced after a new virtualenv is activated.

# data science
pip install ipython
pip install jupyter

pip install numpy
pip install pandas

pip install sympy
pip install nose

pip install scipy
pip install scikit-image
pip install scikit-learn

pip install matplotlib

# c extensions
pip install cython

# functional programming
pip install fn
pip install toolz
pip install cytoolz
pip install multipledispatch
pip install pyrsistent

# devops
pip install ansible
pip install cookiecutter
pip install colorlog
pip install docker
pip install raven
pip install thefuck
pip install tox
pip install versioneer

# database
pip install happybase
pip install mysql-connector-python-rf
pip install pymongo
pip install redis
pip install sqlalchemy

# web development
pip install jinja2
pip install lxml
pip install sanic
pip install twisted
pip install uvloop

# mq
pip install celery
pip install flower
pip install kafka-python

# web crawler
pip install frontera
pip install scrapy

# misc.
pip install mitmproxy
pip install jedi
pip install sphinx

