version: '3'
services:
    sentry:
        container_name: dc-sentry
        depends_on:
            - redis
            - postgres
        environment:
            SENTRY_POSTGRES_HOST: postgres
            SENTRY_DB_NAME: sentry
            SENTRY_DB_PASSWORD: xxxx
            SENTRY_DB_USER: sentry
            SENTRY_REDIS_HOST: redis
            SENTRY_SECRET_KEY: 'eg62num()1edt%jr5ym00l!7p1qt0a^k^qatv@zds(&22qk&&o'
        image: getsentry/sentry:latest
        links:
            - redis
            - postgres
        networks:
            - sentry
        ports:
            - 9000:9000
        restart: always
        tty: true
        volumes:
            - ./data-sentry-files:/var/lib/sentry/files
            - ./data-sentry-sentry:/etc/sentry
    sentry-cron:
        command: run cron
        container_name: dc-sentry-cron
        depends_on:
            - redis
            - postgres
        environment:
            SENTRY_POSTGRES_HOST: postgres
            SENTRY_DB_NAME: sentry
            SENTRY_DB_PASSWORD: xxxx
            SENTRY_DB_USER: sentry
            SENTRY_REDIS_HOST: redis
            SENTRY_SECRET_KEY: 'eg62num()1edt%jr5ym00l!7p1qt0a^k^qatv@zds(&22qk&&o'
        image: getsentry/sentry:latest
        links:
            - redis
            - postgres
        networks:
            - sentry
        restart: always
        tty: true
        volumes:
            - ./data-sentry-sentry:/etc/sentry
    sentry-worker:
        command: run worker
        container_name: dc-sentry-worker
        depends_on:
            - redis
            - postgres
        environment:
            SENTRY_POSTGRES_HOST: postgres
            SENTRY_DB_NAME: sentry
            SENTRY_DB_PASSWORD: xxxx
            SENTRY_DB_USER: sentry
            SENTRY_REDIS_HOST: redis
            SENTRY_SECRET_KEY: 'eg62num()1edt%jr5ym00l!7p1qt0a^k^qatv@zds(&22qk&&o'
        image: getsentry/sentry:latest
        links:
            - redis
            - postgres
        networks:
            - sentry
        restart: always
        tty: true
        volumes:
            - ./data-sentry-sentry:/etc/sentry
    redis:
        container_name: dc-sentry-redis
        expose:
            - '6379'
        image: redis:alpine
        networks:
            - sentry
        restart: always
        tty: true
        volumes:
            - ./data-redis:/data
    postgres:
        container_name: dc-sentry-postgres
        expose:
            - '5432'
        environment:
            POSTGRES_USER: sentry
            POSTGRES_PASSWORD: xxxx
        image: postgres:alpine
        networks:
            - sentry
        restart: always
        tty: true
        volumes:
            - ./data-postgres:/var/lib/postgresql/data
networks:
    sentry:
        driver: bridge
