# Create Docker Network

# docker network create \
#     --driver macvlan \
#     --subnet 10.0.0.0/8 \
#     --gateway 10.0.0.1  \
#     --opt parent enp0s31f6 \
#     pub_net

version: '3'
services:
    sentry:
        container_name: dc-sentry
        depends_on:
            - redis
            - postgres
        environment:
            SENTRY_POSTGRES_HOST: postgres
            SENTRY_DB_NAME: sentry
            SENTRY_DB_PASSWORD: xxxx
            SENTRY_DB_USER: sentry
            SENTRY_REDIS_HOST: redis
            SENTRY_SECRET_KEY: 'eg62num()1edt%jr5ym00l!7p1qt0a^k^qatv@zds(&22qk&&o'
        expose:
            - '9000'
        image: sentry:latest@sha256:07bcbe90687cbe2ee49a3f62a70faecc5dd62c2b8651720bed7868900ae2128c
        links:
            - redis
            - postgres
        networks:
            pub_net:
                ipv4_address: 10.0.20.20
        restart: always
        tty: true
        volumes:
            - ./sentry-files:/var/lib/sentry/files
            - ./sentry-sentry:/etc/sentry
    sentry-cron:
        command: run cron
        container_name: dc-sentry-cron
        depends_on:
            - redis
            - postgres
        environment:
            SENTRY_POSTGRES_HOST: postgres
            SENTRY_DB_NAME: sentry
            SENTRY_DB_PASSWORD: xxxx
            SENTRY_DB_USER: sentry
            SENTRY_REDIS_HOST: redis
            SENTRY_SECRET_KEY: 'eg62num()1edt%jr5ym00l!7p1qt0a^k^qatv@zds(&22qk&&o'
        image: sentry:latest@sha256:07bcbe90687cbe2ee49a3f62a70faecc5dd62c2b8651720bed7868900ae2128c
        links:
            - redis
            - postgres
        networks:
            pub_net:
                ipv4_address: 10.0.20.23
        restart: always
        tty: true
        volumes:
            - ./sentry-sentry:/etc/sentry
    sentry-worker:
        command: run worker
        container_name: dc-sentry-worker
        depends_on:
            - redis
            - postgres
        environment:
            SENTRY_POSTGRES_HOST: postgres
            SENTRY_DB_NAME: sentry
            SENTRY_DB_PASSWORD: xxxx
            SENTRY_DB_USER: sentry
            SENTRY_REDIS_HOST: redis
            SENTRY_SECRET_KEY: 'eg62num()1edt%jr5ym00l!7p1qt0a^k^qatv@zds(&22qk&&o'
        image: sentry:latest@sha256:07bcbe90687cbe2ee49a3f62a70faecc5dd62c2b8651720bed7868900ae2128c
        links:
            - redis
            - postgres
        networks:
            pub_net:
                ipv4_address: 10.0.20.24
        restart: always
        tty: true
        volumes:
            - ./sentry-sentry:/etc/sentry
    redis:
        container_name: dc-sentry-redis
        expose:
            - '6379'
        image: redis:latest@sha256:6b9f935e89af002225c0dcdadf1fd74245b4cc1e3e91222f7e4769c236cf80d4
        networks:
            pub_net:
                ipv4_address: 10.0.20.21
        restart: always
        tty: true
        volumes:
            - ./redis-data:/data
    postgres:
        container_name: dc-sentry-postgres
        expose:
            - '5432'
        environment:
            POSTGRES_USER: sentry
            POSTGRES_PASSWORD: xxxx
        image: postgres:latest@sha256:1d26fae6c056760ed5aa5bb5d65d155848f48046ae8cd95c5b26ea7ceabb37ad
        networks:
            pub_net:
                ipv4_address: 10.0.20.22
        restart: always
        tty: true
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
networks:
    pub_net:
        external: true
