version: "3"
services:
  rabbitmq:
    container_name: dc-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root 
      RABBITMQ_DEFAULT_PASS: xxxxxxxx
    image: rabbitmq:management
    networks:
      - nw-rabbitmq
    ports:
      - "15672:15672"
    restart: always
    tty: true
    volumes:
      - "./rabbitmq:/var/lib/rabbitmq"

networks:
  nw-rabbitmq:
    driver: bridge
