# Create Docker Network

# docker network create \
#     --driver macvlan \
#     --subnet 10.0.0.0/8 \
#     --gateway 10.0.0.1  \
#     --opt parent enp0s31f6 \
#     pub_net

version: "3"
services:
    mysql:
        container_name: dc-mysql
        environment:
            MYSQL_ROOT_PASSWORD: xxxx
        expose:
            - "3306"
        image: mysql:latest@sha256:038f5f6ea8c8f63cfce1bce9c057ab3691cad867e18da8ad4ba6c90874d0537a
        networks:
            pub_net:
                ipv4_address: 10.0.30.0
        restart: always
        tty: true
        volumes:
            - ./mysql-data:/var/lib/mysql
    phpmyadmin:
        container_name: dc-phpmyadmin
        depends_on:
            - mysql
        environment:
            MYSQL_ROOT_PASSWORD: xxxx
            PMA_HOST: mysql
        expose:
            - "80"
        image: phpmyadmin/phpmyadmin:latest@sha256:0d3eaec30b333ba90ff89eb529521236454714064a41ca80f23f9a37f9d75e60
        links:
            - mysql
        networks:
            pub_net:
                ipv4_address: 10.0.30.1
        restart: always
        tty: true
        volumes:
            - ./phpmyadmin-sessions:/sessions
networks:
    pub_net:
        external: true
