version: "3"
services:
    mysql:
        container_name: dc-mysql
        environment:
            MYSQL_ROOT_PASSWORD: xxxx
        image: mysql:5.6
        networks:
            - mysql
        ports:
            - 3306:3306
        restart: always
        tty: true
        volumes:
            - ./mysql-data:/var/lib/mysql
    phpmyadmin:
        container_name: dc-phpmyadmin
        depends_on:
            - mysql
        environment:
            MYSQL_ROOT_PASSWORD: xxxx
            PMA_HOST: mysql
        image: phpmyadmin/phpmyadmin:latest
        links:
            - mysql
        networks:
            - mysql
        ports:
            - 80:80
        restart: always
        tty: true
        volumes:
            - ./phpmyadmin-sessions:/sessions
networks:
    mysql:
        driver: bridge
