version: "3"
services:
    neo4j:
        container_name: dc-neo4j
        image: neo4j:latest
        networks:
            - neo4j
        ports:
            - 7474:7474
            - 7687:7687
        restart: always
        tty: true
        # volumes:
        #     - ./neo4j-conf:/conf
        #     - ./neo4j-data:/data
        #     - ./neo4j-logs:/logs
        #     - ./neo4j-plugins:/plugins
        #     - ./neo4j-ssl:/ssl
networks:
    neo4j:
        driver: bridge
