# Create Docker Network

# docker network create \
#     --driver macvlan \
#     --subnet 10.0.0.0/8 \
#     --gateway 10.0.0.1  \
#     --opt parent enp0s31f6 \
#     pub_net

version: "3"
services:
    neo4j:
        container_name: dc-neo4j
        expose:
            - "7474"
            - "7687"
        image: neo4j:latest@sha256:8f262ce6bddd0aaa1b51d60f32703e73c39a1ac4c05e78f894dbc9c2aef3ad19
        networks:
            pub_net:
                ipv4_address: 10.0.30.200
        restart: always
        tty: true
        volumes:
            - ./neo4j-conf:/conf
            - ./neo4j-data:/data
            - ./neo4j-logs:/logs
            - ./neo4j-plugins:/plugins
            - ./neo4j-ssl:/ssl
networks:
    pub_net:
        external: true
