version: "3"
services:
    # https://hub.docker.com/_/mongo/
    mongo:
        container_name: dc-mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: xxxxxxxx
        image: mongo:latest@sha256:3a09cd85fb4e76f1d5832f9ea1d4e7481f76e807389b7d8ea6ac4d4ba96f83e5
        networks:
            - mongo
        ports:
            - 27017:27017
        restart: on-failure
        tty: true
        volumes:
            - ./mongo-db:/data/db
    # https://hub.docker.com/r/mongoclient/mongoclient/
    mongoclient:
        container_name: dc-mongoclient
        depends_on:
            - mongo
        environment:
            MONGO_URL: mongodb://root:xxxxxxxx@mongo:27017/admin
        image: mongoclient/mongoclient:latest@sha256:c7dd001df7244d741e20f9cac48664d17dc58b963ece48811c0d25661f205be2
        links:
            - mongo
        networks:
            - mongo
        ports:
            - 3000:3000
        restart: on-failure
        tty: true
        volumes:
            - ./mongoclient-db:/data/db
    # https://hub.docker.com/_/mongo-express/
    mongo-express:
        container_name: dc-mongodb-express
        depends_on:
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: xxxxxxxx
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: mongo
        image: mongo-express:latest@sha256:f225ec6052b09c11a74746f71e15d6066d40db0344bff15b9f3480f797f8c23f
        links:
            - mongo
        networks:
            - mongo
        ports:
            - 8081:8081
        restart: on-failure
        tty: true

networks:
    mongo:
        driver: bridge
