# Create Docker Network

# docker network create \
#     --driver macvlan \
#     --subnet 10.0.0.0/8 \
#     --gateway 10.0.0.1  \
#     --opt parent enp0s31f6 \
#     pub_net

version: '3'
services:
    mongo:
        container_name: dc-mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: xxxxxxxx
        expose:
            - '27017'
        image: mongo:latest@sha256:c6d2b2f8c054210db26b492bab81ffab171ee54eb58925fa98fabb4faca3a9cb
        networks:
            pub_net:
                ipv4_address: 10.0.30.250
        restart: always
        tty: true
        volumes:
            - ./mongo-db:/data/db
    mongoclient:
        container_name: dc-mongoclient
        depends_on:
            - mongo
        environment:
            MONGO_URL: mongodb://root:xxxxxxxx@mongo
        expose:
            - '3000'
        image: mongoclient/mongoclient:latest@sha256:40afc9d75ca855785ae0fde68e7be0ecb44a9ce7f24cdbeaf37d647170225837
        links:
            - mongo
        networks:
            pub_net:
                ipv4_address: 10.0.30.251
        restart: always
        tty: true
        volumes:
            - ./mongoclient-db:/data/db
    mongo-express:
        container_name: MongoDB-express
        depends_on:
            - mongo
        expose:
            - '8081'
        image: mongo-express:latest@sha256:6ef3fa1d9b9cb5ff186e1230a8ba2e4882391e6fdf83e50d39f94ab74a4ba935
        links:
            - mongo
        networks:
            pub_net:
                ipv4_address: 10.0.30.252
        restart: always
        tty: true
networks:
    pub_net:
        external: true
