version: "3"
services:
    # https://hub.docker.com/_/mongo/
    mongo:
        container_name: dc-mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: xxxxxxxx
        image: mongo:latest
        networks:
            - mongo
        ports:
            - 27017:27017
        restart: always
        tty: true
        volumes:
            - ./mongo-db:/data/db
    # https://hub.docker.com/r/mongoclient/mongoclient/
    mongoclient:
        container_name: dc-mongoclient
        depends_on:
            - mongo
        environment:
            MONGO_URL: mongodb://root:xxxxxxxx@mongo:27017/admin
        image: mongoclient/mongoclient:latest
        links:
            - mongo
        networks:
            - mongo
        ports:
            - 3000:3000
        restart: always
        tty: true
        volumes:
            - ./mongoclient-db:/data/db
    # https://hub.docker.com/_/mongo-express/
    mongo-express:
        container_name: dc-mongodb-express
        depends_on:
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: xxxxxxxx
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: mongo
        image: mongo-express:latest
        links:
            - mongo
        networks:
            - mongo
        ports:
            - 8081:8081
        restart: always
        tty: true

networks:
    mongo:
        driver: bridge
